### PR TITLE
Cleaned Dialogues esp in xEdit and forwarded USLEEP edits

### PR DESCRIPTION
**Pull request by ThisIsPatrick**
`Undeleting: [REFR:000D93C5] (places NorVineWall03NoCol [STAT:0003A1FA] in GRUP Cell Temporary Children of GuardianStones [CELL:00009B91] (in Tamriel "Skyrim" [WRLD:0000003C] at 0,-15))
[Undeleting and Disabling References done]  Processed Records: 849, Undeleted Records: 1, Elapsed Time: 00:00
Removing: BonestrewnCrestExterior02 [CELL:0000BA25] (in Tamriel "Skyrim" [WRLD:0000003C] at 32,-3)
Removing: dunPOITundraMarshDog "Meeko" [NPC_:000D95E9]
Removing: [REFR:000F5772] (places FXMistLow01Adjust [MSTT:00016441] in GRUP Cell Temporary Children of ShorsStoneRedbellyMine "Redbelly Mine" [CELL:0001382E])
Removing: [REFR:0005B5BF] (places Barrel02Static [STAT:0010C0E3] in GRUP Cell Temporary Children of RiverwoodAlvorsHouse "Alvor and Sigrid's House" [CELL:000133C8])
[Removing "Identical to Master" records done]  Processed Records: 849, Removed Records: 4, Elapsed Time: 00:00`

**Further notes:**
- SexLab_Dialogues edits SprigganRace [00013204], but does not forward an edit by Dawnguard.esm ( _DLC1WerewolfFeedExclude [KYWD:02015FD3]_ )
- The Slave Hair headparts are set to playable, they will show up in the race menu. Is this necessary?

### CODE REVIEW

**Comment by ThisIsPatrick** [comment]
Based off commit [79b7e0cc2cea691ceedcf98427fdd0576e9a4ea6](https://github.com/SkyrimLL/SDPlus/commit/79b7e0cc2cea691ceedcf98427fdd0576e9a4ea6)

**Comment by SkyrimLL** [comment]
> Based off commit [79b7e0cc2cea691ceedcf98427fdd0576e9a4ea6](https://github.com/SkyrimLL/SDPlus/commit/79b7e0cc2cea691ceedcf98427fdd0576e9a4ea6)

Ok. I am away until Sunday night. Let me make sure I didn't change the esp after pushing that commit and I will merge your changes.

**Comment by SkyrimLL** [comment]
So I had to abort and roll back this change on my end today, as the esp is introducing a CTD with Runtime Error every time I go to sleep. Maybe the binary file was affected by Github somehow?

**Comment by ThisIsPatrick** [comment]
I uploaded it through my browser using GitHub's upload file option, if that makes any difference.

**Comment by ThisIsPatrick** [comment]
I was unable to reproduce your crash.
Minimal mods, default mod settings. Tested sleeping in a paid inn bed.

Could you try cleaning the esp yourself with xEdit or compare your previous esp to mind in xEdit?

**Comment by SkyrimLL** [comment]
It's not the first time an esp cleanup causes crashes on my end. Maybe it is something else in my setup.. no idea what. I will take a look. Can you create an issue with the list of edits you made?

**Pull request merged**
